---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: staging
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: asia-south1-docker.pkg.dev/model-axe-117106/my-repository/nodeimage:1.5
        ports:
        - name: http
          containerPort: 7000
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: staging
spec:
  type: NodePort
  selector:
    app: express
  ports:
  - protocol: TCP
    targetPort: 7000
    port: 3000 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: staging
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /devops
          pathType: Prefix
          backend:
            service:
                name: express
                port:
                  number: 3000
