
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote}}
  namespace: {{ .Release.Namespace | quote}}
  labels:
    {{- range $key, $val := .Values.labels }}
      {{ $key }}: {{ $val | quote }}
    {{- end}}

spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- range $key, $val := .Values.labels }}
      {{ $key }}: {{ $val | quote }}
      {{- end}}
  template:
    metadata:
      labels:
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val | quote }}
        {{- end}}
    spec:
      containers:
      - name: {{ .Release.Name | quote}}
        image: {{ .Values.image.repository| quote}}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort}}
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name | quote}}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.service.type}}
  selector:
    app: express
  ports:
  - protocol: TCP
    targetPort: {{ .Values.service.targetPort}}
    port: {{ .Values.service.port}} 

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.Ingress.name | quote}}
  namespace: {{ .Release.Namespace | quote}}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: {{ .Values.Ingress.path}}
          pathType: Prefix
          backend:
            service:
                name: {{ .Release.Name | quote}}
                port:
                  number: {{ .Values.service.port}}
